algoritmo "semnome"
// Função : Algoritmo para somar 2 numeros
// Autor :
// Data : 07/03/2023
// Seção de Declarações 
var
n1, n2, soma : inteiro
inicio
// Seção de Comandos 
escreval("Digite um número")
leia(n1)
escreval("Digite um número")
leia(n2)
soma := n1 + n2
escreval("A soma de ",n1," e ",n2," = ", soma)
// desafio na mensagem final tem que mostra tb os numeros digitados
// exemplo: A soma de 6 e 4 = 10
fimalgoritmo
